# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  gluetun:
    image: ghcr.io/kreigan/gluetor:${GLUETOR_VERSION:-latest}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - &qbt_port ${WEBUI_PORT:-8080}
      - &torrent_port ${TORRENTING_PORT:-6881}
    ports:
      - ${WEBUI_PORT:-8080}:${WEBUI_PORT:-8080}
    environment:
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY:?wireguard private key is not set}
      WIREGUARD_ENDPOINT_IP: ${WIREGUARD_ENDPOINT_IP:?wireguard endpoint ip is not set}
      WIREGUARD_PUBLIC_KEY: ${WIREGUARD_PUBLIC_KEY:?wireguard public key is not set}
      WIREGUARD_ADDRESSES: ${WIREGUARD_ADDRESSES:?wireguard address is not set}
      TZ: &TZ ${TZ:-Other/UTC}
      WEBUI_PORT: *qbt_port
    restart: always
    pull_policy: always

  qbt:
    image: lscr.io/linuxserver/qbittorrent:${QBITTORRENT_VERSION:-latest}
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      WEBUI_PORT: *qbt_port
      TORRENTING_PORT: *torrent_port
      TZ: *TZ
    network_mode: "service:gluetun"
    volumes:
      - ${QBT_CONFIG:?configuration directory is not set}:/config
      - ${QBT_DOWNLOADS:?downloads directory is not set}:/data/nas-media
    restart: always
    pull_policy: always
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    labels:
      autoheal: true
